language: node_js
env:
  global:
    - CXX=g++-4.8
    - RAW_ROLES_QUOTA=123
    - PUBLIC_AUTHORIZED_STAFF_SHEET_ID=123
    - RAW_FORM_RESPONSE_SHEET_ID=123
    - GATE_GATECHECK_SHEET_ID=123
    - ADMIN_LATE_DEPARTURES_SHEET_ID=123
    - ADMIN_STAFF_LIST_SHEET_ID=123
    - ADMIN_PARSED_FORM_RESPONSES_SHEET_ID=123
    - RAW_PREPAID_TRANSACTIONS_SHEET_ID=123
    - ADMIN_PREPAID_SHEET_ID=123
    - PUBLIC_EARLY_ARRIVALS_SHEET_ID=123
    - PUBLIC_LATE_DEPARTURES_SHEET_ID=123
    - PUBLIC_ROLES_QUOTA_SHEET_ID=123
    - ADMIN_ALL_PASSES_SHEET_ID=123
    - BULK_STAFF_TRANSACTION_SHEET_ID=123

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run build
