language: node_js
env:
  global:
    - CXX=g++-4.8
    - ADMIN_ROLES_QUOTA_SHEET_ID=123
    - AUTHORIZED_STAFF_SHEET_ID=123
    - FORM_RESPONSE_SHEET_ID=123
    - GATE_CHECK_SHEET_ID=123
    - LATE_DEPARTURES_SHEET_ID=123
    - NAMES_SHEET_ID=123
    - PARSED_FORM_RESPONSES_SHEET_ID=123
    - PREPAID_RAWDATA_SHEET_ID=123
    - PREPAID_SHEET_ID=123
    - PUBLIC_EARLY_ARRIVALS_SHEET_ID=123
    - PUBLIC_LATE_DEPARTURES_SHEET_ID=123
    - PUBLIC_ROLES_QUOTA_SHEET_ID=123
    - ROLES_SHEET_ID=123
    - BULK_STAFF_TRANSACTION_SHEET_ID=123
    - SKIPPER_SHEET_ID=123

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run build
